const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    local: {
      email: { type: String },
      emailVerified: { type: Boolean },
      normalizedEmail: { type: String },
      password: { type: String, select: false },
    },
    username: { type: String },
    discordId: { type: String },
    discordToken: { type: String, select: false },
    avatar: { type: Number, default: 1 },
    rank: { type: String, default: "user" },
    balance: { type: Number, default: 0 },
    vault: {
      amount: { type: Number, default: 0 },
      expireAt: { type: Date },
    },
    stats: {
      bet: { type: Number, default: 0 },
      won: { type: Number, default: 0 },
      played: { type: Number, default: 0 },
      deposit: { type: Number, default: 0 },
      depositCount: { type: Number, default: 0 },
      withdraw: { type: Number, default: 0 },
    },
    leaderboard: {
      points: { type: Number, default: 0 },
    },
    limits: {
      betToWithdraw: { type: Number, default: 0 },
      blockAffiliate: { type: Boolean, default: false },
      blockTip: { type: Boolean, default: false },
      blockWithdraw: { type: Boolean, default: false },
      limitTip: { type: Number, default: 0 },
      blockSponsor: { type: Boolean, default: false },
      blockLeaderboard: { type: Boolean, default: false },
      blockPromo: { type: Boolean, default: false },
    },
    claimedKeys: { type: Array, default: [] },
    rewards: {
      dailyCaseLastClaimed: { type: Date, default: null },
    },
    rakeback: {
      daily: {
        earned: { type: Number, default: 0 },
        available: { type: Number, default: 0 },
        lastClaimed: { type: Date, default: null },
      },
      weekly: {
        earned: { type: Number, default: 0 },
        available: { type: Number, default: 0 },
        lastClaimed: { type: Date, default: null },
      },
      monthly: {
        earned: { type: Number, default: 0 },
        available: { type: Number, default: 0 },
        lastClaimed: { type: Date, default: null },
      },
    },
    affiliates: {
      code: { type: String },
      customCommission: { type: Number },
      referred: { type: Number, default: 0 },
      wager: { type: Number, default: 0 }, //Total wager by referred users * houseEdge
      totalClaimed: { type: Number, default: 0 },
      available: { type: Number, default: 0 }, // Wager by referred users * houseEdge -> not claimed yet
      generated: { type: Number, default: 0 }, // Generated by this user -> wager * houseEdge
      referrer: { type: mongoose.Schema.ObjectId, ref: "User" },
      lastClaimed: { type: Date },
    },
    anonymous: { type: Boolean, default: false },
    ips: [
      {
        address: { type: String },
        createdAt: { type: Date, default: Date.now },
      },
    ],
    growIds: { type: Array, default: [] },
    cryptoAddresses: { type: Array, default: [] },
    mute: {
      expire: { type: Date },
      reason: { type: String },
    },
    ignoreList: { type: Array, default: [] },
    favouriteSlots: { type: Array, default: [] },
    whitelist: { type: Boolean, default: false },
    ban: {
      expire: { type: Date },
      reason: { type: String },
    },
    lastEmail: { type: Date },
    verifiedAt: { type: Date },
    updatedAt: { type: Date, default: Date.now },
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

// userSchema.index({ username: 1 }, { collation: { locale: 'en', strength: 2 } });

module.exports = mongoose.model("User", userSchema);
